[package]
name = "Dr-Ones-drone"
version = "1.0.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
rand = "0.8"
toml = "0.8"

indexmap = "1.7.0"

wg_2024 = { git = "https://github.com/WGL-2024/WGL_repo_2024.git", features = [
    "serialize",
    "debug",
] }
